// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sexupgaavdaaghqcritf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleHVwZ2FhdmRhYWdocWNyaXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDQ4NzksImV4cCI6MjA2NDc4MDg3OX0.kts39TgWVckYX7iAjvlNBOUEMPF8_tyiQYbyX8LhOOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);